//console.log(Math.random());
//console.log(Math.floor(Math.random() * (1000 - 500 + 1)) + 500);
//console.log(Math.floor(Math.random() + (100  ) ));
//console.log(Math.floor(Math.random() + (100  ) ));
let max=100;
let min=50;
console.log(Math.floor(Math.random() * ( max ) ));
console.log(Math.floor(Math.random() * (max  ) ));
console.log(Math.floor(Math.random() * (max  ) ));
console.log(Math.floor(Math.random() * (max  ) ));
console.log(Math.floor(Math.random() * (max  ) ));
console.log(Math.floor(Math.random() * (max - min + 1)) + min);
//console.log(Math.floor(Math.random() + (max  ) ));
//console.log(Math.floor(Math.random() + (max  ) ));
//console.log(Math.floor(Math.random() + (max  ) ));
//console.log(Math.floor(Math.random() + (max  ) ));
//console.log(Math.floor(Math.random() + (max  ) ));
//console.log(Math.floor(Math.random() * (100 - 10 + 1)) + 10);
